FROM php:7.2-fpm

MAINTAINER zhetc linweisk@aliyun.com

RUN set -ex; \
    cp /etc/apt/sources.list /etc/apt/sources.list.backup && \
    echo "" > /etc/apt/sources.list && \
    echo 'deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster main contrib non-free' > /etc/apt/sources.list && \
    echo 'deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main contrib non-free' >> /etc/apt/sources.list && \
    echo 'deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-backports main contrib non-free' >> /etc/apt/sources.list && \
    echo 'deb https://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates main contrib non-free' >> /etc/apt/sources.list && \
    curl -sfL https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && \
    chmod +x /usr/bin/composer && \
    composer config -g repo.packagist composer https://mirrors.aliyun.com/composer && \
    apt update && apt install -y --no-install-recommends unzip git supervisor \
    libzstd-dev libpng-dev libwebp-dev libjpeg-dev libfreetype6-dev libssl-dev libzip-dev && \
    docker-php-source extract && \
    docker-php-ext-configure gd --with-freetype-dir=/usr/include --with-jpeg-dir=/usr/include --with-webp-dir=/usr/include && \
    docker-php-ext-install -j$(nproc) gd && \
    docker-php-ext-install bcmath zip pdo_mysql && \
    docker-php-source delete && \
    yes | pecl install igbinary redis mongodb swoole-4.8.12 && \
    docker-php-ext-enable igbinary redis mongodb swoole && \
    apt clean -y && \
    rm -rf \
    /var/cache/debconf/* \
    /var/lib/apt/lists/* \
    /var/log/* \
    /var/tmp/* \
    /tmp/* && \
    mkdir -p /var/log/supervisor

WORKDIR /www
