FROM php:8.1-fpm-alpine

MAINTAINER zhetc linweisk@aliyun.com

RUN set -ex; \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
    curl -sfL https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && \
    chmod +x /usr/bin/composer && \
    composer config -g repo.packagist composer https://mirrors.aliyun.com/composer && \
    apk add --no-cache --update --virtual .build-deps autoconf g++ make && \
    apk add --no-cache libzip-dev libpng-dev libwebp-dev libjpeg-turbo-dev freetype-dev libressl-dev zstd-dev libstdc++ \
    unzip git supervisor && \
    docker-php-source extract && \
    docker-php-ext-configure gd --with-freetype=/usr/include --with-jpeg=/usr/include --with-webp=/usr/include && \
    docker-php-ext-install -j$(nproc) gd && \
    docker-php-ext-install bcmath zip pdo_mysql && \
    docker-php-source delete && \
    yes | pecl install igbinary redis mongodb swoole && \
    docker-php-ext-enable igbinary redis mongodb swoole && \
    apk del .build-deps && \
    rm -rf /var/cache/apk/* \
    /tmp/*

WORKDIR /www