FROM php:7.4-fpm-alpine

MAINTAINER windy yonicsk@aliyun.com

RUN set -ex; \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
    curl -sfL https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && \
    chmod +x /usr/bin/composer && \
#    composer config -g repo.packagist composer https://mirrors.aliyun.com/composer && \
    apk add --no-cache --update --virtual .build-deps autoconf g++ make && \
    apk add --no-cache tzdata supervisor unzip \
    libzip-dev libpng-dev libwebp-dev libjpeg-turbo-dev freetype-dev lz4-dev && \
    docker-php-source extract && \
    docker-php-ext-configure gd --with-freetype=/usr/include --with-jpeg=/usr/include --with-webp=/usr/include && \
    docker-php-ext-install -j$(nproc) gd && \
    docker-php-ext-install bcmath zip pdo_mysql && \
    docker-php-source delete && \
    pecl install igbinary msgpack mongodb && \
    yes | pecl install redis && \
    docker-php-ext-enable igbinary msgpack redis mongodb && \
    apk del .build-deps && \
    rm -rf /var/cache/apk/* \
    /tmp/*

WORKDIR /www
